language: go
go:
  - 1.7
install: make install-ci
env:
  global:
    - TEST_TIMEOUT_SCALE=20 # Set higher timeouts for Travis
    - PACKAGE=github.com/$TRAVIS_REPO_SLUG
    - TEST_TLS_COMMUNICATION=true
sudo: required
dist: trusty
script:
 - make all
